### ISSUE TITLE
Overlapping 'M' in striped boxes

### ISSUE THREAD

**Issue by SicroAtGit** [Fossy-Cats/Git-Buch_EN#32]
The 'M' label should be removed from the box. The text box in the foreground with the label 'M' is sufficient. This prevents the only partially covered 'M' behind it from being partially visible.

I tried to do it myself, but I don't know how to group ungrouped objects again. I can't select multiple objects of the box with <kbd>Ctrl</kbd> + <kbd>Left mouse button</kbd>. Also, for the diagram `push.dia`, I can't edit the label for the middle and right 'M' box (no text cursor appears).

![OverlappingM1](https://user-images.githubusercontent.com/18380976/140608317-2a279335-8316-493f-b455-a96a4e22977b.png)
![OverlappingM2](https://user-images.githubusercontent.com/18380976/140608318-389b73e7-4a56-4823-8467-9b894db92b95.png)

**Comment by tajmone** [comment]
> The 'M' label should be removed from the box. The text box in the foreground with the label 'M' is sufficient. This prevents the only partially covered 'M' behind it from being partially visible.

OK, I've fixed it. The problem was actually worst than we thought...

In the striped box there was also a stray triangle (a zero-length line with arrow point) that for some unknown reason had landed just behind the 'M' letter, which is probably why they looked so bad (not so much the double M, but the triangle). Removing it was not easy because it was hard to select.

To save time, I've duplicated the whole elements by pasting it around, so its errors propagated too (the double M and the triangle).

There was also a problem with the `topic` box, which hadn't been changed into a single flowchart box (was still using the original box + label). Let me know if they look better now that the background `M` letters are gone.


BTW, this is how the striped box was composed:

- A flowchart box in the background (with one of the stripes colours as its BG), and the 'M' that needed removing (was there for alignment purposes).
- The various stripe object (rectangles) on top of it.
- An empty box frame to cover the border of the flowchart box, since it was overlapped by the stripes (need this box frame to ensure transparency).
- The 'M' as a text-label to ensure it's on top of the stripes (that covered the original 'M').

The objects weren't grouped in `merge-base-commit.dia`, but they were in `push.dia` (grouped objects as showed as "Group with X objects" in the Diagram Tree).

Anyhow, I can see a huge difference already. After removing the background 'M', the letter stopped looking like a Pixel Art font. But then I noticed a strange double border on the left side, and discovered the triangle (once you're aware of it, you can't stop seeing it).

-------------------------------------------------------------------------------

> I tried to do it myself, but I don't know how to group ungrouped objects again.

With overlapping objects the best way to select them is via the Diagram Tree viewer. You can always send an object to the back to work on the one below, so you can view it better, and then re-order their layering (via Object > Send back, etc.) before grouping them again.

> I can't select multiple objects of the box with Ctrl + Left mouse button.

Strange, that's how it's supposed to be done, i.e. you're selecting every object within the rectangle area that you delimit while holding the left button down.

> Also, for the diagram push.dia, I can't edit the label for the middle and right 'M' box (no text cursor appears).

Check that they are not grouped and locked (some grouped objects might contain other grouped objects). I use the <kbd>F2</kbd>keyboard shortcuts to access editing the text, the mouse is not always reliable in the interface.

In any case I'll look into it.

**Comment by SicroAtGit** [comment]
Looks good now.

The problem also exists with the `pull.dia` diagram. There is also an arrowhead hidden behind the 'M'. Sorry, should have made a list of which diagrams have the problem so as not to leave any out.

---

I can now select multiple objects in Dia by pressing <kbd>Shift</kbd> + <kbd>Left mouse button</kbd>.

Selecting objects and their underlying objects to create a group from this constellation is something I need to look at again.

**Comment by tajmone** [comment]
Done!
